### ISSUE TITLE
Android version run failed in main branch

### ISSUE THREAD

**Issue by AlvinChen1028** [pixpark/gpupixel#10]
I try to run it in Android Studio with emulator, but it runs failed. The root cause is: in 'build.gradle', it defines targetSdk to '31', but in the code (GPUPixelSourceCamera.java) is still using the 'Camera' APIs which have been deprecated. Or anything am I doing wrong?

**Comment by gezhaoyou** [comment]
Translation: I will try the emulator and if I can reproduce the issue, I will fix it. If you already have a solution, please write it here.

**Comment by gezhaoyou** [comment]
I have already run it on the emulator, and the demo crashed because the emulator does not have a camera. In the screenshot, there are the error details and information about my emulator device, but it does not report the specific error you mentioned. ![Xnip2024-01-21_11-19-38](https://github.com/pixpark/gpupixel/assets/15272757/8aa4469f-d33c-43d1-81ca-53cdf875d78c)

**Comment by gezhaoyou** [comment]
Please try version 1.0.6 or the newest main branch code. The android app can run emulator now.

**Comment by gezhaoyou** [comment]
Please try version 1.0.6 or the newest main branch code. The android app can run emulator now. See https://github.com/pixpark/gpupixel/commit/b669984ad0d01dde5ff492645b3bc7fab172c94c
![Xnip2024-01-21_15-28-45](https://github.com/pixpark/gpupixel/assets/15272757/6de893b9-3598-4e31-8eec-6334fada5eb3)

**Comment by AlvinChen1028** [comment]
Thanks. It works on emulator with webcam connected in android studio. BTW, rename 'src/util.h' to 'src/Util.h', otherwise, the lib would be compiled failed. And set minSDK from '31' to '34'.
